name: Dependabot Automation
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'nmdra/TickBook'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add labels
        run: |
          gh pr edit "$PR_URL" --add-label "dependencies"
          if [ "${{ steps.metadata.outputs.update-type }}" == "version-update:semver-patch" ]; then
            gh pr edit "$PR_URL" --add-label "patch"
          fi
          if [ "${{ steps.metadata.outputs.update-type }}" == "version-update:semver-minor" ]; then
            gh pr edit "$PR_URL" --add-label "minor"
          fi
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve and Enable Auto-Merge for Patch/Minor Updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
