name: Service - Event

on:
  push:
    branches: [main, Development]
    paths: ['event-service/**']
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
      security-events: write
      actions: read
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service: event-service
      dockerfile: event-service/Dockerfile
      context: ./event-service
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
